# Workflow for Ubuntu (latest).
name: Ubuntu

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      # We do not checkout recursively submodules because
      # we don't need the only submodule we have '3rdparty/dev-tools'.
      - uses: actions/checkout@v2

      - name: Check for bazel
        run: bazel --version

      - name: Build
        run: bazel build --spawn_strategy=local --copt="-g" --strip="never" :flags

      - name: Debug Build using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: bazel test --spawn_strategy=local --copt="-g" --strip="never" --test_output=errors test:flags --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100

      - name: Debug Test using tmate (in failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
